spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Blog-Platform?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: ALWAYS

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  application:
    name: book-management-system
    security:
      jwt:
        secret-key: "26vh4gv265r42vdrt64hv2dr86th4v2ts68h42cse6rg42cr8we4yv2w84"


server:
  port: 8080

logging:
  level:
    root: INFO
    com.example.Book.Management: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
